# general settings
name: Swinhyper_nonhyperL_class_ex1
model_type: FClassModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
# manual_seed: 114514
multitrain: true
round: 6
dataset_random_fetch: true
random_fetch_path: ./datasets/data/score_list_level.csv
val_ratio: 0.2
# if dataset_random_fetch is on, the csv_path would be disbaled in the train and val phase.
# a new csv would be created and saved in the models folder


# dataset and data loader settings
datasets:
  train:
    name: EyeQS
    type: EyeQSClassDataset
    image_folder: ./datasets/data
    csv_path: ./datasets/data/score_list_train.csv
    io_backend:
      type: disk

    full_score: 100
    image_size: !!int 384
    flip: true
    square_cut: true
    augment_ratio: 10
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: testEyeQS
    type: EyeQSClassDataset
    image_folder: ./datasets/data
    csv_path: ./datasets/data/score_list_test.csv
    io_backend:
      type: disk

    full_score: 100
    image_size: 384
    flip: false
    square_cut: true
    augment_ratio: 10
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# network structures
network_g:
  type: SwinTransformer
  img_size: 384
  patch_size: 4
  in_chans: 3
  num_classes: 3 #
  embed_dim: 96
  depths: [2, 2, 18, 2]
  num_heads: [3, 6, 12, 24]
  window_size: 12 # windows here
  mlp_ratio: 4.
  qkv_bias: True
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.1
  ape: False
  patch_norm: True
  use_checkpoint: False

# path
path:
  pretrain_network_g:
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.99
  optim_g:
    type: Adam
    lr: !!float 3e-5
    weight_decay: 0.
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [15000, 30000, 50000, 70000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: 1000  # -1 for no warm up

  # losses
  ce_opt:
    type: CrossEntropyLoss
    loss_weight: !!float 1
    reduction: mean


# validation settings
val:
  val_freq: !!float 2500
  save_img: true

  metrics:
    Accuracy:
      type: calculate_acc
      better: higher
    # Confus_mat: # metric name, can be arbitrary
    #   type: get_confus_matrix
    #   better: higher # use lower/higher to specify
    Precision:
      type: calculate_p
      better: higher
    Recall:
      type: calculate_r
      better: higher
    F1:
      type: calculate_f1
      better: higher



# logging settings
logger:
  print_freq: 2500
  save_checkpoint_freq: !!float 2500
  save_best: true
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500